# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "centos7" do |redhat|
    redhat.vm.box = "centos-7-x86_64"
    redhat.vm.hostname = "centos7"

    # Network Configs
    redhat.vm.network "private_network", ip: "10.10.10.10"
  end
end
